apiVersion: v1
kind: PersistentVolume
metadata:
  name: dasi-pv-storage
  labels:
    type: dasi-storage
spec:
  capacity:
    storage: 6Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dasi-storage
  nfs:
    path: /mnt/store/nfs/files/private/dafab/dasi
    server: 10.40.11.18
  # local:
  #   path: /mnt/dasi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - knot
