apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dasi-pvc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 480Gi
  storageClassName: dasi-storage
