[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydafab"
version = "0.1.0"
description = "Python package for data tools at DaFab EU project."
readme = "README.md"
authors = [{name = "Metin Cakircali"}, {name = "Joshua Harwood"}]
license = {text = "Apache License 2.0"}
requires-python = ">=3.11"
dependencies = [
	"pydasi>=0.3.1",
	"pystac>1.12",
	"pystac-client>0.8",
	"boto3>1.41",
]

[project.optional-dependencies]
dev = [
	"pytest>=8.0.0",
	"myst-nb",
	"sphinx-autoapi",
	"sphinx-rtd-theme",
	"ruff",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
src_paths = ["src"]

[tool.ruff]
line-length = 120
exclude = [".venv", "build", "dist", "docs/_build"]
src = ["src"]

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
