[tool.poetry]
name = "pydafab"
version = "0.1.0"
description = "Python package for data tools at DaFab EU project."
authors = ["Metin Cakircali"]
license = "Apache License 2.0"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

dependencies = ["pydasi>0.0.5", "pystac>1.12", "pystac-client>0.8", "boto3>1.41"]

reportMissingImports = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
src_paths = ["src"]
virtual_env = ".venv"

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
